--------------------------------------------------------
--  파일이 생성됨 - 수요일-7월-29-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APPLY
--------------------------------------------------------

  CREATE TABLE "HR"."APPLY" 
   (	"신청ID" VARCHAR2(20 BYTE), 
	"이름" VARCHAR2(20 BYTE), 
	"사업자번호" VARCHAR2(20 BYTE), 
	"연락처" VARCHAR2(20 BYTE), 
	"부스ID" VARCHAR2(20 BYTE), 
	"부스소개" VARCHAR2(300 BYTE), 
	"첨부파일" VARCHAR2(100 BYTE), 
	"회원ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index APPLY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."APPLY_PK" ON "HR"."APPLY" ("신청ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table APPLY
--------------------------------------------------------

  ALTER TABLE "HR"."APPLY" MODIFY ("회원ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."APPLY" ADD CONSTRAINT "APPLY_PK" PRIMARY KEY ("신청ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."APPLY" MODIFY ("부스ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."APPLY" MODIFY ("연락처" NOT NULL ENABLE);
  ALTER TABLE "HR"."APPLY" MODIFY ("사업자번호" NOT NULL ENABLE);
  ALTER TABLE "HR"."APPLY" MODIFY ("이름" NOT NULL ENABLE);
  ALTER TABLE "HR"."APPLY" MODIFY ("신청ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table APPLY
--------------------------------------------------------

  ALTER TABLE "HR"."APPLY" ADD CONSTRAINT "APPLY_FK1" FOREIGN KEY ("부스ID")
	  REFERENCES "HR"."BOOTH" ("부스ID") ENABLE;
  ALTER TABLE "HR"."APPLY" ADD CONSTRAINT "APPLY_FK2" FOREIGN KEY ("회원ID")
	  REFERENCES "HR"."CUSTOMER" ("ID") ENABLE;
