--------------------------------------------------------
--  파일이 생성됨 - 수요일-7월-29-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOOTH
--------------------------------------------------------

  CREATE TABLE "HR"."BOOTH" 
   (	"부스ID" VARCHAR2(20 BYTE), 
	"부스종류" VARCHAR2(20 BYTE), 
	"대여료" NUMBER(10,0), 
	"대여시작기간" VARCHAR2(20 BYTE), 
	"대여종료기간" VARCHAR2(20 BYTE), 
	"부스크기" VARCHAR2(20 BYTE), 
	"부스상태" VARCHAR2(20 BYTE) DEFAULT '대기', 
	"축제ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BOOTH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."BOOTH_PK" ON "HR"."BOOTH" ("부스ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOOTH
--------------------------------------------------------

  ALTER TABLE "HR"."BOOTH" ADD CONSTRAINT "BOOTH_PK" PRIMARY KEY ("부스ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."BOOTH" MODIFY ("축제ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."BOOTH" MODIFY ("부스상태" NOT NULL ENABLE);
  ALTER TABLE "HR"."BOOTH" MODIFY ("부스크기" NOT NULL ENABLE);
  ALTER TABLE "HR"."BOOTH" MODIFY ("대여종료기간" NOT NULL ENABLE);
  ALTER TABLE "HR"."BOOTH" MODIFY ("대여시작기간" NOT NULL ENABLE);
  ALTER TABLE "HR"."BOOTH" MODIFY ("대여료" NOT NULL ENABLE);
  ALTER TABLE "HR"."BOOTH" MODIFY ("부스종류" NOT NULL ENABLE);
  ALTER TABLE "HR"."BOOTH" MODIFY ("부스ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BOOTH
--------------------------------------------------------

  ALTER TABLE "HR"."BOOTH" ADD CONSTRAINT "BOOTH_FK1" FOREIGN KEY ("축제ID")
	  REFERENCES "HR"."FESTIVAL" ("축제ID") ENABLE;
