--------------------------------------------------------
--  파일이 생성됨 - 수요일-7월-29-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FESTIVAL
--------------------------------------------------------

  CREATE TABLE "HR"."FESTIVAL" 
   (	"축제ID" VARCHAR2(20 BYTE), 
	"축제명" VARCHAR2(20 BYTE), 
	"시작기간" DATE, 
	"종료기간" DATE, 
	"주소" VARCHAR2(20 BYTE), 
	"기관연락처" VARCHAR2(20 BYTE), 
	"축제설명" VARCHAR2(300 BYTE), 
	"첨부파일" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FESTIVAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."FESTIVAL_PK" ON "HR"."FESTIVAL" ("축제ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FESTIVAL
--------------------------------------------------------

  ALTER TABLE "HR"."FESTIVAL" ADD CONSTRAINT "FESTIVAL_PK" PRIMARY KEY ("축제ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."FESTIVAL" MODIFY ("기관연락처" NOT NULL ENABLE);
  ALTER TABLE "HR"."FESTIVAL" MODIFY ("주소" NOT NULL ENABLE);
  ALTER TABLE "HR"."FESTIVAL" MODIFY ("종료기간" NOT NULL ENABLE);
  ALTER TABLE "HR"."FESTIVAL" MODIFY ("시작기간" NOT NULL ENABLE);
  ALTER TABLE "HR"."FESTIVAL" MODIFY ("축제명" NOT NULL ENABLE);
  ALTER TABLE "HR"."FESTIVAL" MODIFY ("축제ID" NOT NULL ENABLE);
