--------------------------------------------------------
--  파일이 생성됨 - 수요일-7월-29-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HOST
--------------------------------------------------------

  CREATE TABLE "HR"."HOST" 
   (	"ID" VARCHAR2(20 BYTE), 
	"PW" VARCHAR2(20 BYTE), 
	"주소" VARCHAR2(100 BYTE), 
	"기관명" VARCHAR2(50 BYTE), 
	"연락처" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."PK_ID" ON "HR"."HOST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table HOST
--------------------------------------------------------

  ALTER TABLE "HR"."HOST" ADD CONSTRAINT "PK_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."HOST" MODIFY ("연락처" NOT NULL ENABLE);
  ALTER TABLE "HR"."HOST" MODIFY ("기관명" NOT NULL ENABLE);
  ALTER TABLE "HR"."HOST" MODIFY ("주소" NOT NULL ENABLE);
  ALTER TABLE "HR"."HOST" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "HR"."HOST" MODIFY ("ID" NOT NULL ENABLE);
